server {
  listen       80;
  server_name  localhost;

  root   /usr/share/nginx/html;
  index  index.html;

  include /etc/nginx/mime.types;

  # Serve static assets and fallback to index.html for SPA routes
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Optional: add security headers
  add_header X-Frame-Options "SAMEORIGIN";
  add_header X-Content-Type-Options "nosniff";
  add_header Referrer-Policy "no-referrer-when-downgrade";
}
